image: gradle:7.1.1-jdk8

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build tarea1:
  stage: build
  script: gradle --build-cache :tarea1:assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - tarea1/build
      - .gradle

test tarea1:
  stage: test
  script: gradle :tarea1:check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - tarea1/build
      - .gradle
