
package com.entrenamosuy.web.publicar;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NoFinalizableExceptionWrapper", targetNamespace = "http://publicar.view.tarea1.entrenamosuy.com/")
public class NoFinalizableExceptionWrapper_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoFinalizableExceptionWrapper faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NoFinalizableExceptionWrapper_Exception(String message, NoFinalizableExceptionWrapper faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public NoFinalizableExceptionWrapper_Exception(String message, NoFinalizableExceptionWrapper faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.entrenamosuy.web.publicar.NoFinalizableExceptionWrapper
     */
    public NoFinalizableExceptionWrapper getFaultInfo() {
        return faultInfo;
    }

}
