
package com.entrenamosuy.web.publicar;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PasswordInvalidaException", targetNamespace = "http://publicar.view.tarea1.entrenamosuy.com/")
public class PasswordInvalidaException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PasswordInvalidaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PasswordInvalidaException_Exception(String message, PasswordInvalidaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PasswordInvalidaException_Exception(String message, PasswordInvalidaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.entrenamosuy.web.publicar.PasswordInvalidaException
     */
    public PasswordInvalidaException getFaultInfo() {
        return faultInfo;
    }

}
