
package com.entrenamosuy.web.publicar;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PublicadorActividad", targetNamespace = "http://publicar.view.tarea1.entrenamosuy.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicadorActividad {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.entrenamosuy.web.publicar.BeanActividad
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDataActividad", targetNamespace = "http://publicar.view.tarea1.entrenamosuy.com/", className = "com.entrenamosuy.web.publicar.GetDataActividad")
    @ResponseWrapper(localName = "getDataActividadResponse", targetNamespace = "http://publicar.view.tarea1.entrenamosuy.com/", className = "com.entrenamosuy.web.publicar.GetDataActividadResponse")
    @Action(input = "http://publicar.view.tarea1.entrenamosuy.com/PublicadorActividad/getDataActividadRequest", output = "http://publicar.view.tarea1.entrenamosuy.com/PublicadorActividad/getDataActividadResponse")
    public BeanActividad getDataActividad(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.entrenamosuy.web.publicar.BeanActividad>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarActividadesAceptadas", targetNamespace = "http://publicar.view.tarea1.entrenamosuy.com/", className = "com.entrenamosuy.web.publicar.ListarActividadesAceptadas")
    @ResponseWrapper(localName = "listarActividadesAceptadasResponse", targetNamespace = "http://publicar.view.tarea1.entrenamosuy.com/", className = "com.entrenamosuy.web.publicar.ListarActividadesAceptadasResponse")
    @Action(input = "http://publicar.view.tarea1.entrenamosuy.com/PublicadorActividad/listarActividadesAceptadasRequest", output = "http://publicar.view.tarea1.entrenamosuy.com/PublicadorActividad/listarActividadesAceptadasResponse")
    public List<BeanActividad> listarActividadesAceptadas();

}
