package com.entrenamosuy.web.publicar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PublicadorActividadService", targetNamespace = "http://publicar.core.entrenamosuy.com/", wsdlLocation = "http://localhost:9128/webservices?wsdl")
public class PublicadorActividadService
    extends Service
{

    private final static URL PUBLICADORACTIVIDADSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLICADORACTIVIDADSERVICE_EXCEPTION;
    private final static QName PUBLICADORACTIVIDADSERVICE_QNAME = new QName("http://publicar.core.entrenamosuy.com/", "PublicadorActividadService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9128/webservices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICADORACTIVIDADSERVICE_WSDL_LOCATION = url;
        PUBLICADORACTIVIDADSERVICE_EXCEPTION = e;
    }

    public PublicadorActividadService() {
        super(__getWsdlLocation(), PUBLICADORACTIVIDADSERVICE_QNAME);
    }

    public PublicadorActividadService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICADORACTIVIDADSERVICE_QNAME, features);
    }

    public PublicadorActividadService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICADORACTIVIDADSERVICE_QNAME);
    }

    public PublicadorActividadService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICADORACTIVIDADSERVICE_QNAME, features);
    }

    public PublicadorActividadService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicadorActividadService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicadorActividad
     */
    @WebEndpoint(name = "PublicadorActividadPort")
    public PublicadorActividad getPublicadorActividadPort() {
        return super.getPort(new QName("http://publicar.core.entrenamosuy.com/", "PublicadorActividadPort"), PublicadorActividad.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicadorActividad
     */
    @WebEndpoint(name = "PublicadorActividadPort")
    public PublicadorActividad getPublicadorActividadPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicar.core.entrenamosuy.com/", "PublicadorActividadPort"), PublicadorActividad.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICADORACTIVIDADSERVICE_EXCEPTION!= null) {
            throw PUBLICADORACTIVIDADSERVICE_EXCEPTION;
        }
        return PUBLICADORACTIVIDADSERVICE_WSDL_LOCATION;
    }

}
