package com.entrenamosuy.web.publicar;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PublicadorActividad", targetNamespace = "http://publicar.core.entrenamosuy.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface PublicadorActividad {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.core.entrenamosuy.com/PublicadorActividad/holaRequest", output = "http://publicar.core.entrenamosuy.com/PublicadorActividad/holaResponse")
    public String hola();

}
