
package com.entrenamosuy.web.publicar;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SinCategoriaExceptionWrapper", targetNamespace = "http://publicar.view.tarea1.entrenamosuy.com/")
public class SinCategoriaExceptionWrapper_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SinCategoriaExceptionWrapper faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SinCategoriaExceptionWrapper_Exception(String message, SinCategoriaExceptionWrapper faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SinCategoriaExceptionWrapper_Exception(String message, SinCategoriaExceptionWrapper faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.entrenamosuy.web.publicar.SinCategoriaExceptionWrapper
     */
    public SinCategoriaExceptionWrapper getFaultInfo() {
        return faultInfo;
    }

}
